services:
  postgres:
    image: postgres:latest
    container_name: logit_postgres
    environment:
      POSTGRES_DB: logit_test
      POSTGRES_USER: integral
      POSTGRES_PASSWORD: password
    ports:
      - 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
